# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blackScholesPDE <- function(strike, maturity, spot, type, param, N, M, american, B) {
    .Call(`_pricing_blackScholesPDE`, strike, maturity, spot, type, param, N, M, american, B)
}

blackScholesPDE_chain <- function(strike, maturity, spot, type, param, N, M, american) {
    .Call(`_pricing_blackScholesPDE_chain`, strike, maturity, spot, type, param, N, M, american)
}

blackScholesPDE_surface <- function(strike, maturity, spot, type, param, N, M, american) {
    .Call(`_pricing_blackScholesPDE_surface`, strike, maturity, spot, type, param, N, M, american)
}

blackScholesGreeks_chain <- function(strike, maturity, spot, type, param, N, M, american) {
    .Call(`_pricing_blackScholesGreeks_chain`, strike, maturity, spot, type, param, N, M, american)
}

blackScholesGreeks <- function(strike, maturity, spot, type, param, N, M, american) {
    .Call(`_pricing_blackScholesGreeks`, strike, maturity, spot, type, param, N, M, american)
}

